name: API
on:
  push:
    branches: [main]
    paths:
      - api/**

jobs:
  build:
    name: Lint and Build API

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [18.x, 20.x]
        os: [ubuntu-latest]

    defaults:
      run:
        working-directory: ./api

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
        #   cache: "pnpm"
        #   cache-dependency-path: api/package-lock.json

      - name: Install deps (with cache)
        run: pnpm install

      - name: Node.js cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/build
          key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('**/pnpm-lock.yaml') }}-nodejs

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build
