name: Frontend
on:
  push:
    branches: [main]
    # paths:
    #   - frontend/**

defaults:
  run:
    working-directory: ./frontend

jobs:
  build:
    name: Lint and Typecheck Frontend

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [18.x, 20.x]
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8

      - name: Use Node ${{ runner.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ runner.node }}
          cache: "pnpm"

      - name: Install deps (with cache)
        run: pnpm install

      - name: Next.js cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ runner.node }}-${{ hashFiles('**/pnpm-lock.yaml') }}-nextjs

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck
